# Generated by Django 5.0.6 on 2024-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skeleton",
            name="endMessage",
            field=models.TextField(blank=True, null=True),
        ),
    ]
