# Generated by Django 5.0.6 on 2024-07-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_alter_skeleton_endmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="accepted",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="options",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
