# Generated by Django 5.0.6 on 2024-07-20 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_skeleton_instance"),
        ("live", "0013_alter_socialuser_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="instance",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="live.instance",
            ),
        ),
    ]
