# Generated by Django 5.0.6 on 2024-07-20 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_response_instance"),
        ("live", "0013_alter_socialuser_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="live.socialuser",
            ),
        ),
    ]
