# Generated by Django 5.0.6 on 2024-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_alter_answer_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="skeleton",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
