# Generated by Django 5.0.6 on 2024-07-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="hash",
            field=models.CharField(
                default="3e43178fd8f246de", editable=False, max_length=16, unique=True
            ),
        ),
    ]
