# Generated by Django 5.0.6 on 2024-07-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0002_alter_instance_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="hash",
            field=models.CharField(
                default="3a13028cc18043cc", editable=False, max_length=16, unique=True
            ),
        ),
    ]
