# Generated by Django 5.0.6 on 2024-07-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0003_alter_instance_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instance",
            old_name="type",
            new_name="auth_type",
        ),
        migrations.RenameField(
            model_name="instance",
            old_name="status",
            new_name="instance_status",
        ),
        migrations.AlterField(
            model_name="instance",
            name="hash",
            field=models.CharField(
                default="90ea4bdc50f64a3c", editable=False, max_length=16, unique=True
            ),
        ),
    ]
