# Generated by Django 5.0.6 on 2024-07-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0004_rename_type_instance_auth_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instance",
            old_name="auth_type",
            new_name="instance_auth_type",
        ),
        migrations.AlterField(
            model_name="instance",
            name="hash",
            field=models.CharField(
                default="87f6b51da5d84b19", editable=False, max_length=16, unique=True
            ),
        ),
    ]
