# Generated by Django 5.0.6 on 2024-07-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0005_rename_auth_type_instance_instance_auth_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instance",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="instance",
            name="hash",
            field=models.CharField(
                default="ff3732b6d0fd460a", editable=False, max_length=16, unique=True
            ),
        ),
    ]
