# Generated by Django 5.0.6 on 2024-07-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0006_rename_user_instance_user_id_alter_instance_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instance",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="instance",
            name="hash",
            field=models.CharField(
                default="e456036826aa43a8", editable=False, max_length=16, unique=True
            ),
        ),
    ]
