# Generated by Django 5.0.6 on 2024-07-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0007_rename_user_id_instance_user_alter_instance_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="hash",
            field=models.CharField(
                default="74994bc1b66841d2", editable=False, max_length=16, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="instance_auth_type",
            field=models.IntegerField(
                choices=[
                    (1, "Open to All"),
                    (2, "Open within Ogranization"),
                    (4, "Open to Specific Users"),
                ],
                default=1,
            ),
        ),
    ]
