# Generated by Django 5.0.6 on 2024-07-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0008_alter_instance_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="hash",
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
    ]
