# Generated by Django 5.0.6 on 2024-07-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0010_socialuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialuser",
            name="email",
        ),
        migrations.AddField(
            model_name="socialuser",
            name="username",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
