# Generated by Django 5.0.6 on 2024-07-08 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0011_remove_socialuser_email_socialuser_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialuser",
            old_name="user_scoial_type",
            new_name="user_social_type",
        ),
    ]
