# Generated by Django 5.0.6 on 2024-07-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0012_rename_user_scoial_type_socialuser_user_social_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="socialuser",
            constraint=models.UniqueConstraint(
                fields=("instance", "username"), name="unique_instance_username"
            ),
        ),
    ]
